<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="/assets/img/favicon.ico">

    <title>Slimish</title>

    <!-- Custom styles for this template -->
    <link href="/style.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="inner">
        <h3 class="masthead-brand">Slimish</h3>
        <ul class="nav masthead-nav">
            <li>
                <a href="/">Home</a>
            </li>
        </ul>
    </div>
</div>

<div class="site-wrapper">
    <div class="cover-container">
        <div class="cover">
            <?php
                if (isset($partial)) :
                    \Slim\Slim::getInstance()->render(sprintf('partials/%s.phtml', $partial));
                endif;
            ?>
        </div>
    </div>
</div>

<div class="mastfoot">
    <p>Copyright &copy; <?php echo date('Y'); ?> <a href="http://www.griasolutions.com">Gria Solutions</a>.
        All rights reserved.</p>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/assets/vendor/jquery/dist/jquery.min.js"></script>
<script src="/assets/vendor/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="/assets/releng/js/scripts.js"></script>
</body>
</html>