<h1>Slim Skeleton Application</h1>
<p class="lead">
    Use this template (based on <a href="http://getbootstrap.com/examples/starter-template/">that template</a>) as a way to quickly start any new <a href="http://www.slimframework.com/">Slim</a> project.<br>
    Have fun, and don't do anything overtly ridiculous!<br>
    <a class="slimish-icon" href="https://github.com/guillermoandrae/slim-skeleton-app"><i class="fa fa-3x fa-github"></i></a>
</p>